management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


  instance:
    preferIpAddress: true

spring:
  application:
    name: testsproject
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      current_session_context_class: thread
      enable_lazy_load_no_trons: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      bindings:
        consumer-in-0:
          destination: chat-consumer-topic
        producer-out-0:
          destination: chat-producer-topic

  flyway:
    enabled: true
    locations: classpath:db/migration
debug: true

