#  Назначение:
#  Этот конфигурационный файл (application.yml) предназначен для настройки микросервиса,
#  который регистрируется на Eureka Server и взаимодействует с другими сервисами через Kafka.
#
#  Основные возможности:
#   • Регистрация в Eureka Server (service discovery)
#   • Работа с PostgreSQL через Spring Data JPA и Hibernate
#   • Автоматическое создание / обновление схемы БД
#   • Отправка и получение сообщений через Kafka с использованием Spring Cloud Stream
#   • Автоматическая конфигурация Spring Boot
#
#  Компоненты конфигурации:
#   - server: конфигурация порта веб-приложения
#   - eureka: регистрация микросервиса в Eureka Server
#   - spring.datasource: настройки подключения к PostgreSQL
#   - spring.jpa: поведение ORM (Hibernate)
#   - spring.cloud.stream.kafka: интеграция с Apache Kafka
#
#  Применение:
#   Файл должен располагаться в ресурсах (src/main/resources/application.yml)
#   и автоматически подхватывается Spring Boot при старте.
server:
  # Порт, на котором будет запускаться веб-сервер (по умолчанию 8080)
  port: 8080

# EUREKA CLIENT CONFIGURATION
eureka:
  client:
    serviceUrl:
      # Адрес Eureka Server (использует переменную окружения EUREKA_URL, если задана)
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    # Отображать IP вместо hostname при регистрации в Eureka
    preferIpAddress: true

# SPRING APPLICATION SETTINGS
spring:
  application:
    # Уникальное имя приложения для Eureka и Spring Context
    name: eureka-client

  # DATABASE CONFIGURATION (PostgreSQL)
  datasource:
    # Драйвер JDBC для PostgreSQL
    driver-class-name: org.postgresql.Driver
    # URL подключения к базе данных
    url: jdbc:postgresql://localhost:5433/postgres
    # Имя пользователя для подключения к базе
    username: postgres
    # Пароль пользователя для подключения к базе
    password: postgres

  # JPA / HIBERNATE CONFIGURATION
  jpa:
    # Настройки JPA / Hibernate
    properties:
      hibernate:
        # Диалект Hibernate для PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
      # Определяет стратегию управления сессиями Hibernate
      current_session_context_class: thread
      # Разрешает ленивую загрузку вне транзакции
      enable_lazy_load_no_trans: true
    # Показывать SQL-запросы в консоли
    show-sql: true
    # Генерировать DDL автоматически (создание/обновление таблиц)
    generate-ddl: true
    hibernate:
      # Автоматическое обновление схемы базы данных
      ddl-auto: update

  # Настройки Kafka и Spring Cloud Stream
  cloud:
    function:
      # Определение функций для Spring Cloud Function:
      # consumer – обработчик входящих сообщений
      # producer – отправитель исходящих сообщений
      definition: consumer;producer
    stream:
      kafka:
        binder:
          # Адрес брокера Kafka
          brokers: localhost:29092
      bindings:
        # Поток входящих сообщений (consumer)
        consumer-in-0:
          destination: consumer-topic
        # Поток исходящих сообщений (producer)
        producer-out-0:
          destination: producer-topic
